version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - noctx
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: redefines-builtin-id
          disabled: true
        - name: unused-parameter
          disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
